---
ID: "f6256f2f-75dc-59c7-8134-22c23c9179d3"
Parent: "5ba40c0f-4d08-5b84-99a6-a3e4259416ca"
Template: "5ba40c0f-4d08-5b84-99a6-a3e4259416ca"
Path: "/sitecore/templates/Project/sitecoresyndicate/Styleguide-FieldUsage-Image/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T020047Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "85258e8a-4063-421b-ac22-1ec94cd19d9b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T020047Z
