---
ID: "85ba25c4-2b4c-5c2d-b9e3-043dae13cf3e"
Parent: "188d3392-e3e1-5117-bf0c-9ab2083c396e"
Template: "188d3392-e3e1-5117-bf0c-9ab2083c396e"
Path: "/sitecore/templates/Project/sitecoresyndicate/Styleguide-FieldUsage-Date/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T020046Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "68f1b886-334c-427b-bb58-4690d689de26"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T020046Z
