---
ID: "0dabd322-c51f-54b4-a717-db42e192b404"
Parent: "19e91bf8-c3d3-5f90-92b5-bc3ab2c4d5a5"
Template: "19e91bf8-c3d3-5f90-92b5-bc3ab2c4d5a5"
Path: "/sitecore/templates/Project/sitecoresyndicate/Styleguide-FieldUsage-Text/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T020049Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cb9ee95a-1fbe-4211-a641-3b7f649f7e54"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T020049Z
