---
ID: "6700b55e-f241-53ac-ba7e-ea298b333401"
Parent: "5dd863f0-499f-5712-a733-b8dec747d8ed"
Template: "5dd863f0-499f-5712-a733-b8dec747d8ed"
Path: "/sitecore/templates/Project/sitecoresyndicate/Styleguide-ItemLink-Item-Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T020043Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e594c869-5ca9-455a-9fe0-879a26e5cc99"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T020043Z
