---
ID: "e1e901a7-93df-58ff-ab82-cc26068852b5"
Parent: "65182fc5-60d8-54d8-814b-7c901815a294"
Template: "65182fc5-60d8-54d8-814b-7c901815a294"
Path: "/sitecore/templates/Project/sitecoresyndicate/Styleguide-FieldUsage-ItemLink/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T020047Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0668a970-6d48-4dda-a015-a61bc9bc47fc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T020047Z
